# Generated by Django 4.1.2 on 2022-10-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id_base', models.AutoField(primary_key=True, serialize=False)),
                ('certificate', models.IntegerField(unique=True, verbose_name='Номер удостоверения')),
                ('full_name', models.CharField(max_length=30, verbose_name='Ф.И.О.')),
                ('title', models.CharField(max_length=20, verbose_name='Звание')),
                ('address', models.CharField(max_length=30, verbose_name='Адрес')),
                ('family_composition', models.CharField(max_length=20, verbose_name='Состав семьи')),
            ],
            options={
                'verbose_name': 'Сотрудникa',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('certificate',),
            },
        ),
    ]
