# Generated by Django 4.1.2 on 2022-10-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incident_Database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='certificate',
            field=models.IntegerField(max_length=7, unique=True, verbose_name='Номер удостоверения'),
        ),
    ]
