# Generated by Django 4.1.2 on 2022-10-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incident_Database', '0005_alter_employees_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='certificate',
            field=models.DecimalField(decimal_places=0, help_text='Не более 7 цифр', max_digits=7, max_length=7, unique=True, verbose_name='Номер удостоверения'),
        ),
    ]
